### PR TITLE
Shallow fix for issue #247 (missing rhx_gis)

### PR DESCRIPTION
**Pull request by tgandor**
I added a default of empty string for the rhx_gis shared data member.

### CODE REVIEW

**Comment by tgandor** [comment]
I have no idea why the UT hang after running practically all of them - Travis failed because it hanged.

**Comment by hashark** [comment]
when I applied the same fix on the latest code I had the same problem. It may be related to the agent. 
When I used the code from the 2.3.4 release it worked. It may be the latest code addition...

**Comment by bskim45** [comment]
any chance to get merged @althonos

**Comment by althonos** [comment]
Thanks @tgandor , if that's all that is needed for it to work I'm fine merging. Will do a new release shortly.

**Pull request merged**
