### PR TITLE
Fix issue #150 Login does not work with `v1.0` 

### PR DESCRIPTION
**Pull request by AbysmalBiscuit**
Change cached cookies file format to use pickle dump.

### CODE REVIEW

**Comment by AbysmalBiscuit** [comment]
@althonos I have also found that in the `setup.cfg` file on line 50:
```
    instaLooter = instalooter.cli:main
```
Will throw the following error when attempting to uninstall the package with pip:
```
configparser.DuplicateOptionError: While reading from '<???>' [line  3]: option 'instalooter' in section 'console_scripts' already exists
```
I believe this is due to the file like object generator used in `configparser.py`, since `instalooter` and `instaLooter` are marked as having the same entry point, so it attempts to remove the same directories/files twice and fails on the second attempt.

Should I fix this in my PR as well?

Also, I have not previously worked with codecov/coverage in general, beyond simple unittests; hence I don't know how to improve my PR to meet the codecov requirements. :/

**Comment by AbysmalBiscuit** [comment]
I have just tested my PR on Windows 10 Python and WSL, both work fine.

**Comment by althonos** [comment]
@AbysmalBiscuit: Tested as well, works indeed. I created a new test account that'll I use in CI.

Don't worry about codacy and codecov too much: as the saying goes, *the real fool is not the one who ignores the linter, but the one who fixes everything* (well, maybe I just came with that one).

My only concern is: why was it necessary to switch to `JSON` for the cookies ? I'm not really favorable to this, since deserializing JSON (and pickle as well, for that matter) is a security breach in Python. I don't see why you needed to change the cookie jar, since you're only changing the cookie values.

I'll merge shortly (in the meantime, you can add yourself to the contributors section of the documentation ([`docs/source/index.rst`](https://github.com/althonos/InstaLooter/blob/master/docs/source/index.rst)) !

**Comment by althonos** [comment]
Oh, and yes, if you could fix the entry points that would be great. I think it's a windows specific issue however, since I could install and uninstall just fine on my Linux.

**Comment by althonos** [comment]
@AbysmalBiscuit : I actually got it to work only with:
```python
 session = session or Session()
        homepage = "https://www.instagram.com/"
        login_url = "https://www.instagram.com/accounts/login/ajax/"
        data = {'username': username, 'password': password}

        session.headers.update({
            'Host': 'www.instagram.com',
            'Origin': 'https://www.instagram.com',
            'Referer': 'https://www.instagram.com',
            'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) \
                           Gecko/20100101 Firefox/57.0",
            'X-Instagram-AJAX': '1',
            'X-Requested-With': 'XMLHttpRequest'
        })

        with session.get(homepage) as res:
            session.headers.update({'X-CSRFToken': res.cookies['csrftoken']})
        time.sleep(5 * random.random()) # nosec

        with session.post(login_url, data=data, allow_redirects=True) as login:
            session.headers.update({'X-CSRFToken': login.cookies['csrftoken']})
            time.sleep(5 * random.random()) # nosec
            if not login.status_code == 200:
                raise SystemError("Login error: check your connection")
    ...
```

**Comment by AbysmalBiscuit** [comment]
@althonos The reason why I had switched to using pickle and then json, was because I had goofed a bit by not realizing that the following was actually unnecessary:
```python
session.cookies['ig_vw'] = '1536'
session.cookies['ig_pr'] = '1.25'
session.cookies['ig_vh'] = '772'
session.cookies['ig_or'] = 'landscape-primary'
```
After I updated the code to be based on the latest LevPasha/instabot.py, my brain failed to register that those cookies were added after you get the login response. Since `LWPCookieJar` doesn't support adding cookies in the same way as `RequestsCookieJar`, sticking with `RequestsCookieJar` and saving it in a different format seemed a simpler way dealing with the problem than changing the cookiejar type and then saving.

Are you sure that deserializing JSON is a security breach? (I know it is for pickle due to a vulnerability to code injection attacks.)
It isn't mentioned in the documentation and from Googling I haven't found mention that it is.


As for the entry points in `setup.cfg`. I use ArchLinux as a daily driver and that's where I initially had the problem with uninstalling it. I have tried installing it with the `--user` option in pip, but even when it installs to my home directory I get the same error. 
On Windows 10 I had the same problem with WSL, but I haven't tested uninstalling it with a regular python installation on Windows.


I don't mind if you just change that method and reject the PR. :)
Just make sure to use:
```python
session = session or cls._init_session()
```
Since otherwise it will create a `Session()` object with a `RequestsCookieJar` and not an `LWPCookieJar` which will throw an error when trying to save it.

My inner completionist couldn't resist a final commit. :p

**Comment by althonos** [comment]
Since you reverted to minimal changes, I don't see anything that's preventing me from merging ;)

I'm probably confusing security issues of JSON with YAML (I think PyYAML has some breaches), but anyway if it's not needed to change the cookie jar I'd rather keep it this way. It was using JSON at some point in the program history, but I believe I changed for a good reason (well, I hope so) !

Thanks for you contribution (I think a lot of users owe you one) !

**Pull request merged**
