### PR TITLE
Feature/add support for customizing download url

### PR DESCRIPTION
**Pull request by bmass02**
# Reason
I needed to grab images with certain aspect ratios. So I added the option of passing in a function to customize from which URL to download the image.

#### Using lambdas (and to grab other image sources from media object)
```python
looter = InstaLooter( directory="Desktop/", ... , custom_photo_url=lambda media: media['thumbnail_src'])
```

#### Grab custom image size (as in examples)
```python
def custom_photo_url(media):
  cleaning_regex = re.compile(r"(s[0-9x]*/)?(e[0-9]*)/")
  return cleaning_regex.sub('s320x320/', media['display_src'])

looter = InstaLooter( directory="thumbnails/", ... , custom_photo_url=custom_photo_url)
```

#### Create a custom cropped image
```python
def square_photo_url(media):
  cleaning_regex = re.compile(r"(s[0-9x]*/)?(e[0-9]*)/")
  dims = media['dimensions']

  smaller_dim, y_offset, x_offset = "", 0, 0
  if media['height'] > media['width']:
    smaller_dim = str(media["width"])
    y_offset = (media['height'] - media['width'])/2
  else:
    smaller_dim = str(media["height"])
    x_offset = (media['width'] - media['height'])/2

  crop_url_params = 'c{}.{}.{}.{}/'.format( str(x_offset), str(y_offset), smaller_dim, smaller_dim)
  return cleaning_regex.sub( crop_url_params, media['display_src'])

looter = InstaLooter( directory="square_images/", ... , custom_photo_url=square_photo_url)
```

### CODE REVIEW

**Comment by althonos** [comment]
Sweet ! I'll merge and refactor a bit.

**Comment by althonos** [comment]
PS: I renamed the argument `url_generator` to reflect the idea this is supposed to be a callable, rather than a static variable.

**Comment by bmass02** [comment]
@althonos If you wanted me to write some tests for it I can, but I figured you had a specific structure to tests.

**Comment by althonos** [comment]
I don't actually, I juste use unittest (the test folder is an organized mess) :smile:
But I ended up doing it myself because I refactored the code at tad in the meanwhile.

**Comment by bmass02** [comment]
Awesome! I just looked at your test for the square media. Just a note: "s320x320" won't always return a square media. [Here](https://scontent-mia1-1.cdninstagram.com/t51.2885-15/s320x320/18251932_1835000630156151_8434485015294771200_n.jpg) is an example of requesting a 320x320 image that isn't actually 320x320. The "thumbnail_src" value of the media object will return a link to an image that is always square.

**Comment by althonos** [comment]
Fixed, thanks.

**Pull request merged**
