### PR TITLE
Add private account checker

### PR DESCRIPTION
**Pull request by mohan3d**
Add private account checker in `download()` before initiating workers.
trying to solve #6

### CODE REVIEW

**Comment by althonos** [comment]
I think the check belongs to the `medias` method, since it is used by `download`... But nice job finding a fix :)

**Comment by mohan3d** [comment]
I thought it would be better to early check if it's private account, before initiating the workers (so no need to kill them later).

**Comment by althonos** [comment]
Yeah but if someone uses the InstaLooter within Python and runs the medias
iterator over a private profile, it will still do an infinite loop... Maybe
best thing would be to have the check both in .download() and .medias().

**Comment by althonos** [comment]
Also, wouldn't a person downloading medias from a private picture he has
access rights to (with credentials) be kicked out nevertheless with the
method you used ? Just want to know, since I have no account to try.

Le 18 déc. 2016 14:02, "Martin Larralde" <larralde.martin@gmail.com> a
écrit :

> Yeah but if someone uses the InstaLooter within Python and runs the medias
> iterator over a private profile, it will still do an infinite loop... Maybe
> best thing would be to have the check both in .download() and .medias().
>

**Comment by mohan3d** [comment]
You are right about the the two problems :)

I didn't think about the first one, will anyone use instaLooter to only fetch list of pictures urls ? instead of downloading them ?

for the second problem if it's private account, only followers can view it (this can fix it).

**Comment by althonos** [comment]
1. Submitter of #3 was using the Python API of InstaLooter, so there's definitely a demand for this.

2. I think here we have to distinguish between public/private and viewable/unviewable. For the first one you can get it with the "is private" value, for the other you can infer it from the length of the medias list returned by the entry data. What we want here is to know within the pages() iterator if  the profile is viewable or not by the user (public profile or private but the user is logged in and follows this profile) before starting the loop, or else we'll keep going forward without finding anything.

Or do you have another suggestion on how to handle this ?

IMO it is the pages() that should do the check and break the loop if there is no other page to get...

Maybe just breaking the main loop in pages() would be enough :)

**Comment by mohan3d** [comment]
I agree with your approach, I am closing this PR now.
waiting for your fix :)

**Pull request closed without merging**
