### PR TITLE
Candidate fix for hashtag json structure change issue #130

### PR DESCRIPTION
**Pull request by gffde3**
Re-opening because travis failed due to connectivity issue with test_issue_84 (pretty certain it's unrelated to anything I did between the last correct test case and now).

### CODE REVIEW

**Comment by gffde3** [comment]
Travis is pooping the bed and has connectivity issues to instagram so it arbitrarily fails tests when it can't retrieve the data for a test. So I'm just going to leave it here... ¯\_(ツ)_/¯

Identical codebase in both the following travis builds:

https://travis-ci.org/althonos/InstaLooter/builds/325698949 - Fails on 3.5, passes on 3.6
https://travis-ci.org/althonos/InstaLooter/builds/325701521 - Passes on 3.5, fails on 3.6

When I run the unit tests locally it's fine (expected warning about a non-existent user):

Launching py.test with arguments PycharmProjects/InstaLooter_git/tests in PycharmProjects\InstaLooter_git\tests

================== test session starts =======================
platform win32 -- Python 3.5.4, pytest-3.3.2, py-1.5.2, pluggy-0.6.0
rootdir: \PycharmProjects\InstaLooter_git, inifile:
collected 42 items
test_batch.py                                                           [  2%]
test_cli.py .                                                        [ 14%]
test_issues.py ...Usage:
    instaLooter (login | logout)
    instaLooter batch <batch_file>
    instaLooter <profile> [<directory>] [options]
    instaLooter (hashtag <hashtag> | post <post_token>) <directory> [options]
    instaLooter (-h | --help | --version | --usage)
Usage:
    instaLooter (login | logout)
    instaLooter batch <batch_file>
    instaLooter <profile> [<directory>] [options]
    instaLooter (hashtag <hashtag> | post <post_token>) <directory> [options]
    instaLooter (-h | --help | --version | --usage)
..                                     [ 64%]
test_looter.py .............
16:29:2 - WARNING - Could not find page of user: akjhdskjhfkjsdhfkjhdskjhfkjdshkfjhsdkjfdhkjdfshdfskhfd
16:29:2 - WARNING - No medias found.
........                                                [ 88%]
test_urlgen.py ..........                                                        [ 92%]
test_utils.py ..

================ warnings summary ========================
tests/test_looter.py::TestUtils::test_length_hint_empty
  \PycharmProjects\InstaLooter_git\instaLooter\core.py:351: UserWarning: Could not find page of user: jkshksjdhfjkhdkfhk
    warnings.warn("Could not find page of user: {}".format(self.target), stacklevel=1)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
====== 42 passed, 1 warnings in 148.90 seconds ====================
...                                                        [100%]
Process finished with exit code 0

**Comment by althonos** [comment]
@gffde3 : sorry I cannot merge this yet, I need to do a quick review beforehand but this is exam season currently. I should be able to review (and merge hopefully) this weekend.

By the way, neither are my tests well-thought, nor is Travis working fine with Instagram :smile:

**Comment by gffde3** [comment]
Yeah, thats all good. I'm still using it daily so I'll keep an eye on it. I think there may be a couple issues but by and large it's alright.

I did just have an exception come up that was 'NoneType' object has no attribute 'group' but that was because I scraped multiple times for the same date range to see what happened.

Also, I know the exam pain; good luck with them!

**Comment by althonos** [comment]
@gffde3 : Nice work ! I revamped the transformation a tad, and I'll be releasing a new version.
Travis fails because the URL generation feature seems broken, I'll have a look later.

**Pull request merged**
