### PR TITLE
Save metadata to JSON file

### PR DESCRIPTION
**Pull request by AndCycle**
save metadata to separate JSON file makes post-processing much easier

this is just a rough implement, should have lot's room for improvement.

### CODE REVIEW

**Comment by althonos** [comment]
@AndCycle : sorry I did not give any feedback about this earlier, this sound promising !
Could you add tests as well so that coverage stays up ?

**Comment by AndCycle** [comment]
I have to confess I am not familiar with unitest and handling github conflict.

**Comment by althonos** [comment]
I'll do it, then, no problem !

**Comment by AndCycle** [comment]
https://github.com/althonos/InstaLooter/pull/88/commits/4d87176e8977c16f8adbf800d262e60ae982713a#diff-11d694fc93531ee44f1bfc8244b1da9cL474

you might wanna take a look at this part I removed, 
I can't remember why I removed that part, 

that should go to a separate commit which I failed to do it on spot.

**Comment by althonos** [comment]
Codecov is going mad because I fixed the coverage report, so I'm positive for merging since tests still go fine. Anything you may want to add, @AndCycle ?

**Comment by AndCycle** [comment]
@althonos looks good to me, I got nothing on hand to add.

**Comment by althonos** [comment]
@AndCycle, I added you to the *greetings* section in the documentation. Thanks for this PR !

**Pull request merged**
